### ISSUE TITLE
I/Os from nvme devices are not traced?

### ISSUE THREAD

**Issue by wenbinzeng** [HewlettPackard/LinuxKI#19]
Hi Mark,

I am running LinuxKI on a kvm guest with passthrough nvme devices, I/Os are very active but I don't see any of them from nvme devices. Is this expected?

Best regards,
Wenbin

**Comment by MarkCRay** [comment]
Hi Wenbin,

LinuxKI makes use of existing tracepoints in the kernel.  If there's no tracepoint in the kernel path, then we are limited.

Key tracepoints related to I/O are the in the  Block subsystem.   I believe NVME uses its own block driver rather than the standard block drivers, thus the tracepoints are not present.   If the NVME driver uses the SCSI protocol, then you may get trace events using the SCSI events.   You can enable the scsi subsystem when you collect the trace.  Be sure to refer to the LinuxKI MasterClass and there may be an example in the Quick Reference Guide.      

In the past, there were I/O accelerator cards (FusionIO PCIe flash before NVMe came out) where you could tell it to use the standard Linux block devices by setting use_workgroup parameter to 3.    I'm not sure that option works anymore.  

Beyond that, then you have to rely on system call traces and potentially interrupts and sched_switch events if there are tasks waiting for the I/O to complete.  

Best Regards,

Mark
