### ISSUE TITLE
likit.ko module says that scsi_dispatch_cmd_start and scsi_dispatch_cmd_done events could not be initialized

### ISSUE THREAD

**Issue by mhudec** [HewlettPackard/LinuxKI#20]
When I load linuxki kernel module, it says that it cannot initialize scsi_dispatch_cmd_start and scsi_dispatch_cmd_done events. Is this something I should be worried about?

```
# dmesg -T | grep -i liki
...
[Wed Apr 24 09:35:32 2019] LiKI: tracing starting up...
[Wed Apr 24 09:35:32 2019] LiKI: event scsi_dispatch_cmd_start could not be initialized
[Wed Apr 24 09:35:32 2019] LiKI: event scsi_dispatch_cmd_done could not be initialized
[Wed Apr 24 09:35:32 2019] LiKI: tracing was set up successfully
[Wed Apr 24 09:35:48 2019] LiKI: tracing shutting down...
[Wed Apr 24 09:35:48 2019] LiKI: shut down successfully
```

I am using linuxki version 5.9 on HPE ProLiant DL580 Gen9 with SUSE Linux Enterprise Server for SAP Applications 12 SP2 and with SUSE PTF kernel 4.4.120-92.70.1.15108.1.TEST.1086194-default (differences against ordinary 4.4.120-92.70.1 are below).

```
# rpm -qa linuxki*
linuxki-5.9-1.noarch

# cat /etc/os-release
NAME="SLES_SAP"
VERSION="12-SP2"
VERSION_ID="12.2"
PRETTY_NAME="SUSE Linux Enterprise Server for SAP Applications 12 SP2"
ID="sles_sap"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles_sap:12:sp2"

# uname -r
4.4.120-92.70.1.15108.1.TEST.1086194-default

# dmidecode -s system-product-name
ProLiant DL580 Gen9

# rpm -qi kernel-default-4.4.120-92.70.1.15108.1.TEST.1086194.x86_64 --changelog | less
Name        : kernel-default
Version     : 4.4.120
Release     : 92.70.1.15108.1.TEST.1086194
Architecture: x86_64
Install Date: Mon Mar  4 01:39:08 2019
Group       : System/Kernel
Size        : 168310666
License     : GPL-2.0
Signature   : DSA/SHA1, Wed Mar 28 14:19:37 2018, Key ID 6c74ce73b37b98a9
Source RPM  : kernel-default-4.4.120-92.70.1.15108.1.TEST.1086194.nosrc.rpm
Build Date  : Wed Mar 28 14:01:56 2018
Build Host  : sheep54
Relocations : (not relocatable)
Packager    : http://bugs.opensuse.org
Vendor      : SUSE LINUX Products GmbH, Nuernberg, Germany
URL         : http://www.kernel.org/
Summary     : The Standard Kernel
Description :
The standard kernel for both uniprocessor and multiprocessor systems.


Source Timestamp: 2018-03-28 14:36:53 +0200
GIT Revision: aab93cdae9a62006ad5213c78cd79672f2b99c41
GIT Branch: users/slahl/SLE12-SP2/1085656-3
Distribution: SUSE Linux Enterprise PTF
* Wed Mar 28 2018 slahl@suse.de
- fix for last build.

* Wed Mar 28 2018 slahl@suse.com
- bsc#1085656, bsc#1086194
- commit aab93cd
...
```

**Comment by mhudec** [comment]
One note though... likit.ko has been built on other SLES for SAP 12 SP2 (virtual) system with same SUSE PTF kernel and copied over here (we don't have kernel headers etc. installed here for successful kernel module build).

**Comment by MarkCRay** [comment]
This is a problem with LinuxKI on SLES 12 and perhaps later.     I enabled the tracepoints just like I do on every other system and Linux flavor.   

I think that part of the issue is that the scsi driver was moved outside the mainline kernel into the scsi_mod DLKM for that Linux flavor.    

# grep scsi_dispatch_cmd_start /proc/kallsyms
ffffffffa0018410 t ftrace_raw_output_scsi_dispatch_cmd_start    [scsi_mod]
ffffffffa0019850 t ftrace_raw_event_scsi_dispatch_cmd_start     [scsi_mod]
ffffffffa0019960 t perf_trace_scsi_dispatch_cmd_start   [scsi_mod]

What's odd is that the ftrace version (runki -f) will collect the scsi trace records, but of course you'll miss all the added features of the LiKI modules, such as stack traces and hardclock events.  

So far, I haven't been able to enable the trace points for the SCSI events.   Its usually not critical, and if needed, you can collect data with the ftrace module (runki -f).

**Comment by mhudec** [comment]
Thanks for the explanation, Mark. I guess we can close this for the time being.
