### ISSUE TITLE
"Unable to load likit.ko module" as non-root user

### ISSUE THREAD

**Issue by impulse200** [HewlettPackard/LinuxKI#30]
I have set up sudo for non-root user to run kiinfo. But this user is getting this error about kernel module.
I worked around this by adding "/sbin" directory to the user's PATH. But probably it is better to use fully qualified path in [likis.c](https://github.com/HewlettPackard/LinuxKI/blob/5b04f4b36fd85593cea628f04886a2f1dc6df68e/src/kiinfo/likis.c#L97)
Or probe for insmod/rmmod location on startup.

**Comment by MarkCRay** [comment]
Thanks for your feedback!  I've made the change to likis.c and will include it in the 6.1 version.   Since its not critical, it may be another month or two before I release the 6.1 version.   Note the runki script will set the PATH value to include /usr/sbin and /sbin, so we only see this when running kiinfo with the -live or -a <secs> options for realtime tracing.

**Comment by MarkCRay** [comment]
FIxed in version 6.1 released on 04/19/2020
