### ISSUE TITLE
Don't hammer path in profile.d

### ISSUE THREAD

**Issue by utopiabound** [HewlettPackard/LinuxKI#8]
/etc/profile.d/linuxki.sh should not destroy PATH it should do the following:
```
PATH=$PATH:/opt/linuxki
```

Also linuxki rpm should own /etc/profile.d/linuxki.sh and not generate it in %scripts.

**Comment by cvoltz** [comment]
Created pull request #11 to resolve this issue.

**Comment by MarkCRay** [comment]
I've added a linuxki.sh script into the scripts directory with the PATH set appropriately.   The SPEC file was updated to add this to the /etc/profile.d directly rather than managing this in the install/remove scripts. 

I pushed this out as version 5.4.2  since there were no code changes to LiKI or kiinfo.
